/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;
import java.sql.*;
import java.text.*;
import java.text.SimpleDateFormat;
import java.awt.print.*;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import MyFrames.print;
//import MyFrames.print.myPrintable;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import javax.swing.table.TableModel;
import MyFrames.converter;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
/**
 *
 * @author SAMEER
 * 
 */






public class CreateBill extends javax.swing.JInternalFrame {
String c_name;
        String c_address;
        String c_gst;
        String c_street;
        String c_city;
        String gst ;
        String total ;
        String cgst;
        int d;
        int s;
        float gst1;
    /**
     * Creates new form CreateBill
     */
    public CreateBill() {
        initComponents();
        Fillcombo();
        showdate();
        getsum();
        billno();
//        customer();
        AutoCompleteDecorator.decorate(jComboBox2);
        this.setLocation(260, 10);
        
        
    }
    public static boolean confirm() {
    JDialog.setDefaultLookAndFeelDecorated(true);
    int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
      return false;
    } else if (response == JOptionPane.YES_OPTION) {
      return true;
    } else if (response == JOptionPane.CLOSED_OPTION) {
      return false;
    }
    else
        return false;
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("New Bill");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bill No");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Product ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Product Name");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Product Mrp");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("GST");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFrames/7-32.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Remove");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setHighlighter(null);
        jTextField7.setMargin(new java.awt.Insets(2, 4, 2, 2));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFrames/print.png"))); // NOI18N
        jButton4.setText("Print");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Date");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "HSN", "Quantity", "Rate", "GST%", "Per", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Customer Name");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Per");

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("HSN Code");

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("CGST%");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("SGST%");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("IGST%");

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Dispatched through");

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("if CGST/SGST");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(43, 43, 43))
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(39, 54, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(349, 349, 349))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
     customer();
        String tmp=(String)jComboBox2.getSelectedItem();
     String sql1="SELECT * FROM `stock` WHERE `id`=?";
     Connection con;
   PreparedStatement pst;
   ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
            pst=con.prepareStatement(sql1);  
            pst.setString(1, tmp);
            rs1=pst.executeQuery();
            if(rs1.next())
            {
                String add=rs1.getString("pname");
                jTextField3.setText(add);
                String add1=rs1.getString("mrp");
                jTextField4.setText(add1);
                String add2=rs1.getString("gst");
                jTextField9.setText(add2);
                jTextField13.setText(add2);
                String add3=rs1.getString("hsn");
                jTextField6.setText(add3);
                String add4=rs1.getString("per");
                jTextField12.setText(add4);
            }
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible
    
 // bill no
 public void billno()
 {
     String sql1="SELECT COUNT(*) FROM `bill`";
     Connection con;
   PreparedStatement pst;
   ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
            pst=con.prepareStatement(sql1);  
            //pst.setInt(1, 20);
            rs1=pst.executeQuery();
            while(rs1.next())
            {
                //String add3=rs1.getString("pname");
                int g=Integer.parseInt(rs1.getString(1));
                g=g+1;
                jTextField1.setText(String.valueOf(g));
                //String add1=rs1.getString("mrp");
                //jTextField4.setText(add1);
            }
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
 }
 
 public int avail()
 {
     String tmp1=(String)jComboBox2.getSelectedItem();
     String sql1="SELECT * FROM `stock` where id = ?";
     Connection con;
   PreparedStatement pst;
   ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
            pst=con.prepareStatement(sql1);  
            pst.setString(1, tmp1);
            rs1=pst.executeQuery();
            if(rs1.next())
            {
                String add=rs1.getString("available");
                System.out.println(add);
                int add1 = Integer.parseInt(add);
                return add1;
            }
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
     return 0;
 }
 
 
    //insert data into billtable
    public void billupdate()
    {
   String query="INSERT INTO `bill`(bno,`cname`,amt,`pdate`) VALUES("+jTextField1.getText()+",'"+jTextField2.getText()+"',"+jTextField7.getText()+",'"+jTextField8.getText()+"');";
    
       Connection con;    
       Statement st;
       try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
           st = con.createStatement();
           st.executeUpdate(query);
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null ,e);
       }
           }


//Sum of jtable
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
    
                 String s2= jTextField5.getText();//quantity
                 int avail = avail();
                 int str = Integer.parseInt(s2);
//                 if(str>avail){
//                  JOptionPane.showMessageDialog(null, "quantity available is less "+ avail);
//                 }
//                 else{
                 String s1=jTextField4.getText(); //mrp
                
                 String s3=jTextField9.getText();
                  d=Integer.parseInt(s3);
                 float a=Float.parseFloat(s1);
                 int b;
                  b = Integer.parseInt(s2);
                  
                  
                 float c = a * b;
//                 int f = d/100;
//                 System.out.println(f);
//                 float s = c + (c * d/100);
//                 System.out.println(s);
                 //int e = c -((d/100)*c);
                 
                 DecimalFormat decimalFormat = new DecimalFormat("#.##");
float fsum = Float.valueOf(decimalFormat.format(c));
String result=String.valueOf(fsum);
                 model.addRow(new Object[]{jTextField3.getText(),jTextField6.getText(),jTextField5.getText(),jTextField4.getText(),jTextField9.getText(),jTextField12.getText(),result});
                 getsum();
             
                 // Update query;
                 String sql1="UPDATE `stock` SET `available`=`available` - '"+jTextField5.getText()+"' WHERE `id`='"+String.valueOf(jComboBox2.getSelectedItem())+"'";
     Connection con;
   Statement st;
  // ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
            st=con.createStatement();  
            //st.setString(1, tmp);
            st.executeUpdate(sql1);
            
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
//                 }
    }//GEN-LAST:event_jButton1ActionPerformed
      public void getsum()
      {
          if (jCheckBox1.isSelected()){
          float sum=0;
           
          for(int i=0; i<jTable1.getRowCount(); i++)
          {
              sum = sum + Float.parseFloat(jTable1.getValueAt(i,6).toString());
          }
          DecimalFormat decimalFormat = new DecimalFormat("#.##");
float fsum1 = Float.valueOf(decimalFormat.format(sum));
          
          jTextField7.setText(Float.toString(fsum1));
        System.out.print("d "+d+ "fsum "+fsum1);
          gst1 = (fsum1 * d/100);
          float cgst1 = gst1/2;
          float total1 = fsum1 + gst1;
          cgst = Float.toString(cgst1);
          gst = "";
          
          total = Float.toString(total1);
          }else{
               float sum=0;
           
          for(int i=0; i<jTable1.getRowCount(); i++)
          {
              sum = sum + Float.parseFloat(jTable1.getValueAt(i,6).toString());
          }
          DecimalFormat decimalFormat = new DecimalFormat("#.##");
float fsum1 = Float.valueOf(decimalFormat.format(sum));
          
          jTextField7.setText(Float.toString(fsum1));
        System.out.print("d "+d+ "fsum "+fsum1);
          gst1 = (fsum1 * d/100);
          float cgst1 = gst1/2;
          float total1 = fsum1 + gst1;
          cgst = "";
          gst = Float.toString(gst1);
          
          
          total = Float.toString(total1);
          }
          
      }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean result = confirm();
        if(result){
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
            model.removeRow(jTable1.getSelectedRow());
            // Update query;
                 String sql1="UPDATE `stock` SET `available`=`available` + '"+jTextField5.getText()+"' WHERE `pname`='"+jTextField3.getText()+"'";
     Connection con;
   Statement st;
  // ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
            st=con.createStatement();  
            //st.setString(1, tmp);
            st.executeUpdate(sql1);
            
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        billupdate();
        
//        MessageFormat header=new MessageFormat("KALA ENTERPRISES\ta,shdafksdjhbskjdbsjdbvhjsdhfvd\nushdfkjhskjdhskd");
////        MessageFormat main=new MessageFormat("KALA ENTERPRISES\ta,shdafksdjhbskjdbsjdbvhjsdhfvd\nushdfkjhskjdhskd");
//        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
//        
//        try{
//            jTable1.print(JTable.PrintMode.NORMAL, header, footer );
//        }
//        catch(java.awt.print.PrinterException e)
//        {
//            System.err.format("Cannot print %%n",e.getMessage());
//        }
CreateBill ps=new CreateBill();
 Object printitem [][]=ps.getTableData(jTable1);
 ps.setItems(printitem);
       
 PrinterJob pj = PrinterJob.getPrinterJob();
 pj.setPrintable(new myPrintable(),ps.getPageFormat(pj));
       try {
           
            pj.print();
           
            }
        catch (PrinterException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
      jTextField5.setText(model.getValueAt( jTable1.getSelectedRow(), 2).toString());
      jTextField4.setText(model.getValueAt( jTable1.getSelectedRow(), 3).toString());
      jTextField3.setText(model.getValueAt( jTable1.getSelectedRow(), 0).toString());
      jTextField9.setText(model.getValueAt( jTable1.getSelectedRow(), 4).toString());
      jTextField6.setText(model.getValueAt( jTable1.getSelectedRow(), 1).toString());
      jTextField12.setText(model.getValueAt( jTable1.getSelectedRow(), 5).toString());
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

         String s1 = jTextField9.getText();
        int g = Integer.parseInt(s1);
    if(jCheckBox1.isSelected()){
       
               int s = g/2;
               jTextField10.setText(Integer.toString(s));
               jTextField11.setText(Integer.toString(s));
               jTextField13.setText("");
               
    }else{
         jTextField10.setText("");
               jTextField11.setText("");
               jTextField13.setText(Integer.toString(g));
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    public static  String DateFormat = "yyyy-MM-dd";
    public void showdate()
    {
      Calendar cal= Calendar.getInstance();
      SimpleDateFormat format = new SimpleDateFormat(DateFormat);
      jTextField8.setText(format.format(cal.getTime()));

        
    }
    private void Fillcombo()
    {
        String sql;
        sql = "SELECT * FROM `stock`";
    Connection con;
   PreparedStatement ps;
   ResultSet rs;
   
        try
        {
         con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
            ps=con.prepareStatement(sql);  
            rs=ps.executeQuery();
            System.out.print(rs);
            while(rs.next())
            {
                String id=rs.getString("id");
                jComboBox2.addItem(id);
            }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);    
        }
        
    }
    
    private void customer()
    {
        String cust = jTextField2.getText();
        String sql;
        sql = "SELECT * FROM `customer` where `cust_name`='"+jTextField2.getText()+"'";
    Connection con;
   PreparedStatement ps;
   ResultSet rs;
        try
        {
         con=DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "root");
            ps=con.prepareStatement(sql);  
            rs=ps.executeQuery();
            if (!rs.next() ) {
    JOptionPane.showMessageDialog(null, "Customer is not present in database");
} 
            else{
//            while(rs.next())
//            {
                c_name=rs.getString("cust_name");
                System.out.println(c_name);
                c_address=rs.getString("cust_address");
                c_gst=rs.getString("gst_pin");
                c_street=rs.getString("cust_street");
                c_city=rs.getString("cust_city");
//                jComboBox2.addItem(id);
//            }
            }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);    
        }
        
    }
    
    
    static JTable itemsTable;
         public static  int total_item_count=0;
//         public static final String DATE_FORMAT_NOW = "yyyy-MM-dd HH:mm:ss a";
         public static final String DATE_FORMAT_NOW = "dd-MM-yyyy";
         public  static String title[] = new String[] {"Sr.no.","PRODUCT NAME","HSN","QUANTITY","RATE","PER","AMOUNT"};
	
public static void setItems(Object[][] printitem){
        Object data[][]=printitem;
        DefaultTableModel model = new DefaultTableModel();
       //assume jtable has 4 columns.
        model.addColumn(title[0]);
        model.addColumn(title[1]);
        model.addColumn(title[2]);
        model.addColumn(title[3]);
        model.addColumn(title[4]);
        model.addColumn(title[5]);
        model.addColumn(title[6]);
        

        int rowcount=printitem.length;
        
        addtomodel(model, data, rowcount);
       

        itemsTable = new JTable(model);
}

public static void addtomodel(DefaultTableModel model,Object [][]data,int rowcount){
    
        int count=0;
        while(count < rowcount){
         model.addRow(data[count]);
         count++;
        }
        if(model.getRowCount()!=rowcount)
          addtomodel(model, data, rowcount);
        
        System.out.println("Check Passed.");
}
          
public Object[][] getTableData (JTable table) {
    int itemcount=table.getRowCount();
    System.out.println("Item Count:"+itemcount);
    
    DefaultTableModel dtm = (DefaultTableModel) table.getModel();
    int nRow = dtm.getRowCount(), nCol =dtm.getColumnCount();
    Object[][] tableData = new Object[nRow][nCol];
    if(itemcount==nRow)                                        //check is there any data loss.
    {
    for (int i = 0 ; i < nRow ; i++){
        for (int j = 0 ; j < nCol ; j++){
            tableData[i][j] = dtm.getValueAt(i,j);           //pass data into object array.
            }}
     if(tableData.length!=itemcount){                      //check for data losses in object array
     getTableData(table);                                  //recursively call method back to collect data
     }   
    System.out.println("Data check passed");
    }
    else{
                                                           //collecting data again because of data loss.
   getTableData(table);
   }
   return tableData;                                       //return object array with data.
    }     

public static PageFormat getPageFormat(PrinterJob pj){
        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();    
             
                double middleHeight =total_item_count*1.0;  //dynamic----->change with the row count of jtable
                double headerHeight = 5.0;                  //fixed----->but can be mod
        	double footerHeight = 5.0;                  //fixed----->but can be mod
                
                double width = convert_CM_To_PPI(7);      //printer know only point per inch.default value is 72ppi
        	double height = convert_CM_To_PPI(headerHeight+middleHeight+footerHeight); 
            paper.setSize(width, height);
            paper.setImageableArea(
                            convert_CM_To_PPI(0.25), 
                            convert_CM_To_PPI(0.5), 
                            width - convert_CM_To_PPI(0.35), 
                            height - convert_CM_To_PPI(1));   //define boarder size    after that print area width is about 180 points
            
            pf.setOrientation(PageFormat.PORTRAIT);           //select orientation portrait or landscape but for this time portrait
            paper.setSize(8.27*72,11.69*72);
            paper.setImageableArea(0.5*72,0.5*72,8.27*72,11.69*72);
            pf.setPaper(paper);
//            pf.setPaper(paper);    
            
            return pf;
}
        
        
protected static double convert_CM_To_PPI(double cm) {            
	        return toPPI(cm * 0.393600787);            
}

protected static double toPPI(double inch) {            
	        return inch * 72d;            
}

public static String now() {
//get current date and time as a String output   
Calendar cal = Calendar.getInstance();
SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
return sdf.format(cal.getTime());

}

public  class myPrintable implements Printable {
 @Override
  public int print(Graphics graphics, PageFormat pageFormat, 
	                int pageIndex) throws PrinterException {    
	                int result = NO_SUCH_PAGE;    
	                if (pageIndex == 0) {                    
	                Graphics2D g2d = (Graphics2D) graphics;                    
	                             
	                double width = pageFormat.getImageableWidth();
	                double height = pageFormat.getImageableHeight();    
	                g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY()); 
	                Font font = new Font("Arial",Font.BOLD,14);       
	                g2d.setFont(font);
                       
	                
	                try {
	        	/*
                         * Draw Image*
                           assume that printing reciept has logo on top 
                         * that logo image is in .gif format .png also support
                         * image resolution is width 100px and height 50px
                         * image located in root--->image folder 
                         */
                                    int x=100 ;                                        //print start at 100 on x axies
//                                    int y=10;                                          //print start at 10 on y axies
                                    int imagewidth=120;
                                    int imageheight=80;
                                    int y=20;
            
                          BufferedImage read = ImageIO.read(getClass().getResource("kala.png"));
                          g2d.drawImage(read,10,10,imagewidth,imageheight,null);         //draw image
//                          g2d.drawLine(10, y+60, 180, y+60);                          //draw line
                                 }catch (IOException ex) {
                                Logger.getLogger(CreateBill.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        
      		try{
	        /*Draw Header*/
//                    int y=80;
int y=20;
int yShift = 10;
            int headerRectHeight=15;
            int headerRectHeighta=40;
            String bill = jTextField1.getText();
            String date = jTextField8.getText();
            g2d.setFont(new Font("Arial",Font.BOLD,12));
            g2d.drawString("                                           GST INVOICE                                         ",100,15);
            g2d.setFont(new Font("Arial",Font.PLAIN,9));
            g2d.drawString("CELL: 09323563117",460,8);y+=7;
            g2d.drawString("EMAIL: kala.enter@gmail.com",460,18);y+=3;
            g2d.setFont(new Font("Arial",Font.PLAIN,11));
            g2d.drawString("                                     SUBJECT TO THANE JURISDICTION                                        ",90,y);
            g2d.setFont(new Font("Arial",Font.PLAIN,9));
            y+=30;
            g2d.setFont(new Font("Georgia",Font.BOLD,28));
            g2d.drawString("                     KALA ENTERPRISES                                          ",12,y);y+=yShift;
            g2d.drawString("                                                                                            ",12,y);y+=yShift;
            g2d.setFont(new Font("Arial",Font.PLAIN,12));
            g2d.drawString("                               Manufactures & Marketing Spares Of:                                       ",95,y);y+=18;
            g2d.setFont(new Font("Arial",Font.BOLD,13));
            g2d.drawString("                  HOME APPLIANCES AND COMPONENT OF BRASS AND S.S                            ",48,y);y+=yShift;
            g2d.setFont(new Font("Arial",Font.PLAIN,11));
            g2d.drawString("                                                                                            ",12,y);y+=5;
            g2d.drawString("B-1403, RAMESHWAR TOWER-2, NEW GOLDEN NEST PHASE XIV, BHAYANDAR (E) 401105, (MAHARASHTRA)     ",12,y);y+=7;
            g2d.drawString("______________________________________________________________________________________________",12,y);y+=yShift;
            g2d.drawString("                                                                                            ",12,y);y+=10;
//            g2d.drawString(now(),12,y);y+=yShift;
            g2d.setFont(new Font("Arial",Font.BOLD,14));
            g2d.drawString("GSTIN: 27AAJFK6781F1ZZ ",380,y);
             g2d.setFont(new Font("Arial",Font.PLAIN,12));
            g2d.drawString("PARTY'S NAME: ",12,y);g2d.drawString(c_name,105,y);y+=yShift;
            g2d.drawString("                                                                                                ",12,y);y+=yShift;
            
     
            g2d.setFont(new Font("Arial",Font.BOLD,14));
            g2d.drawString("PAN NO: AAJFK6781F",380,y);
            g2d.setFont(new Font("Arial",Font.PLAIN,12));
            g2d.drawString("ADDRESS: ",12,y);g2d.drawString(c_address,105,y);y+=yShift;
            g2d.drawString("                                                                                            ",12,y);y+=5;
             g2d.drawString(c_street,105,y);g2d.drawString("DATE: "+now()+"",380,y);y+=yShift;
             g2d.drawString("                                                                                            ",12,y);y+=5;
            g2d.drawString(c_city,105,y);g2d.drawString("BILL NO: "+bill+"",380,y);y+=yShift;
             g2d.drawString("                                                                                            ",12,y);y+=13;
//             g2d.drawString("                                                                                                ",12,y);y+=yShift;
            g2d.drawString("PARTY's GSTIN: ",12,y);g2d.drawString(c_gst,105,y);g2d.setFont(new Font("Arial",Font.PLAIN,10));g2d.drawString("DISPATCHED THROUGH: "+ jTextField14.getText(),380,y);y+=7;
            g2d.setFont(new Font("Arial",Font.PLAIN,12));
            g2d.drawString("_______________________________________________________________________________________________",12,y);y+=yShift;
//	              g2d.drawString("ABC Shopping Complex", 80,y);  
//	              g2d.drawString("CopyWrite 2009-2014", 900,y+10);                 //shift a line by adding 10 to y value
//	              g2d.drawString(now(), 10, y+20);                                //print date
//	              g2d.drawString("Cashier : admin", 10, y+30);  
	        		
	              /*Draw Colums*/
                      Font font1 = new Font("Arial",Font.PLAIN,14);
                      g2d.setFont(font1);
//                       g2d.drawString("_______________________________________________________________________________________________",12,y);y+=yShift;
//                      g2d.drawLine(10, y, 800, y);
                      g2d.drawString(title[0], 10 ,y+10);
                      g2d.drawString(title[1], 60 ,y+10);
                      g2d.drawString(title[2], 190 ,y+10);
                      g2d.drawString(title[3], 250 ,y+10);
                      g2d.drawString(title[4], 350 ,y+10);
                      g2d.drawString(title[5], 450 ,y+10);
                      g2d.drawString(title[6], 500 ,y+10);y+=12;
                      g2d.drawString("CODE", 190 ,y+10);
g2d.drawString("Rs.  P.", 350 ,y+10);
g2d.drawString("Rs.    P.", 500 ,y+10);
                      g2d.drawLine(10, y+17, 800, y+17);
//                      g2d.drawString("_______________________________________________________________________________________________",12,y);y+=yShift;
                   
	              int cH = 0;
	              TableModel mod = itemsTable.getModel();
                        
	              for(int i = 0;i < mod.getRowCount() ; i++){
	                	/*Assume that all parameters are in string data type for this situation
                                 * All other premetive data types are accepted.
                                */
	                	String quantity = mod.getValueAt(i, 2).toString();
	                	String itemname = mod.getValueAt(i, 0).toString();
                                String mrp = mod.getValueAt(i, 3).toString();
                                String gst = mod.getValueAt(i, 4).toString();
                                String price = mod.getValueAt(i, 6).toString();
                                String hsn = mod.getValueAt(i, 1).toString();
                                String per = mod.getValueAt(i, 5).toString();
	                	
	                	cH = (y+35) + (15*i);                             //shifting drawing line
	                	int j = i+1;
                                String jj = Integer.toString(j);
	                	g2d.drawString(jj, 10, cH);
	                	g2d.drawString(itemname,60, cH);
	                	g2d.drawString(hsn , 190, cH);
                                g2d.drawString(quantity , 257, cH);
                                g2d.drawString(mrp , 350, cH);
                                g2d.drawString(per , 450, cH);
                                g2d.drawString(price , 500, cH);
                              
	                }
                         String s2= jTextField7.getText();
                         float s = Float.parseFloat(total);
                         int a = Math.round(s);
                         String con = converter.convert(a);
	                /*Footer*/
	                font = new Font("Arial",Font.BOLD,14) ;                  //changed font size
	                g2d.setFont(font);
                        int z = 615;
                        g2d.drawLine(10, z, 800, z);z+=15;
                        g2d.setFont(new Font("Arial",Font.PLAIN,9));
                        
                        g2d.drawString("BANK DETAILS: HDFC BANK",10,z);g2d.drawString("State: MAHARASHTRA CODE- 27",220,z);
                         g2d.setFont(new Font("Arial",Font.BOLD,14));
                        g2d.drawString("TOTAL= "+s2+" /-",420,z);z+=12;
                         g2d.setFont(new Font("Arial",Font.PLAIN,9));
                         g2d.drawString("BHAYANDAR(E) BRANCH",10,z);g2d.setFont(new Font("Arial",Font.PLAIN,14));g2d.drawString("CGST "+jTextField10.getText()+"% = "+cgst,420,650);z+=12;
                         g2d.setFont(new Font("Arial",Font.PLAIN,9));
                         g2d.drawString("A/c.No.: 111 6763 00000 32",10,z);g2d.setFont(new Font("Arial",Font.PLAIN,14));g2d.drawString("SGST "+jTextField11.getText()+"% = "+cgst,420,670);z+=12;
                         g2d.setFont(new Font("Arial",Font.PLAIN,9));
                         g2d.drawString("RTGS/Neft Code: HDFC 000 1116",10,z);g2d.setFont(new Font("Arial",Font.PLAIN,14));g2d.drawString("IGST "+jTextField13.getText()+"% = "+gst,420,690);z+=22;
                         g2d.setFont(new Font("Arial",Font.BOLD,14));g2d.drawString("GRAND TOTAL= "+a+" /-",420,710);
                         g2d.setFont(new Font("Arial",Font.BOLD,14));
                         g2d.drawString("Rupees: "+con+" only.",10,725);z+=43;
                         g2d.drawLine(10, z, 800, z);z+=15;
                         g2d.setFont(new Font("Arial",Font.BOLD,10));
                         g2d.drawString("TERMS & CONDITIONS",10,z);g2d.setFont(new Font("Arial",Font.PLAIN,7));g2d.drawString("'I/We hereby certify that my/our registration certificate under",255,z);z+=12;
                         g2d.setFont(new Font("Arial",Font.PLAIN,7));
//                         g2d.drawLine(252,z , 252, z+60);
                         g2d.drawString("1) Our risk and responsibility ceases after goods leave our godown.",10,z);g2d.drawString("the CGST Act 2017 is in force on the date on which the sale of",255,z);z+=12;
                         g2d.drawString("2) Goods once sold will not be taken back or exchanged.",10,z);g2d.drawString("the goods specified in this tax invoice is made by me/us and",255,z);z+=12;
                         g2d.drawString("3) Interest @ 18% per annum will be charged if not paid within a week.",10,z);g2d.drawString("that the transaction of sale covered by this tax invoice has been",255,z);z+=12;
                         g2d.drawString("4) Please pay by 'Payees A/c' Cheque of D.D. drawn on Mumbai bank only.",10,z);g2d.drawString("effected by me/us and it shall be accounted in the turn over of",255,z);z+=12;
                         g2d.drawString("5) Kindly send S.T.D form along with your payment",10,z);g2d.drawString("sales while filing of return and the due tax, if any payable on",255,z);g2d.setFont(new Font("Arial",Font.BOLD,12));g2d.drawString("FOR  K A L A",490,z);z+=12;
                         g2d.setFont(new Font("Arial",Font.PLAIN,7));g2d.drawString("sale has been paid or shall be paid.'",255,z);g2d.setFont(new Font("Arial",Font.BOLD,12));g2d.drawString("ENTERPRISES",490,z);
                         
                        
//                        g2d.drawLine(10, z, 800, z);z+=15;
                        
//                        g2d.drawString("                  Thank You Come Again             ",30, cH+10);
                                                                                 //end of the reciept
            }
            catch(Exception r){
              r.printStackTrace();
            }
  
	                result = PAGE_EXISTS;    
	            }    
	            return result;    
      }
}
   
    
    
    
   /* 
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
